name: Build & Deploy to Cloud Run

on:
  workflow_run:
    workflows: ["Phase 5 - CI Quality Checks"]
    types:
      - completed

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    # üîê This activates Environment secrets
    environment: production

    env:
      PROJECT_ID: devansh-483504
      REGION: asia-south1
      SERVICE_NAME: cloudrun-app
      REPOSITORY: cloudrun-repo
      IMAGE_NAME: cloudrun-app

      DB_USER: appuser
      DB_NAME: appdb

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/367605285780/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: github-actions-sa@devansh-483504.iam.gserviceaccount.com

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        docker build \
          -t asia-south1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest .

    - name: Push Docker image
      run: |
        docker push asia-south1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest

    # =================================================
    # PHASE 8 ‚Äî Environment Secrets ‚Üí Secret Manager
    # =================================================
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image asia-south1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          \
          --set-env-vars DB_USER=$DB_USER,DB_NAME=$DB_NAME \
          \
          --set-secrets \
            DB_PASSWORD=${{ secrets.DB_PASSWORD_SECRET }}:latest, \
            DB_HOST=${{ secrets.DB_HOST_SECRET }}:latest
